package cn.snake.dbkit.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.snake.dbkit.bean.ChatInfoModel;
import cn.snake.dbkit.bean.ContactModel;

import cn.snake.dbkit.dao.ChatInfoModelDao;
import cn.snake.dbkit.dao.ContactModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatInfoModelDaoConfig;
    private final DaoConfig contactModelDaoConfig;

    private final ChatInfoModelDao chatInfoModelDao;
    private final ContactModelDao contactModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatInfoModelDaoConfig = daoConfigMap.get(ChatInfoModelDao.class).clone();
        chatInfoModelDaoConfig.initIdentityScope(type);

        contactModelDaoConfig = daoConfigMap.get(ContactModelDao.class).clone();
        contactModelDaoConfig.initIdentityScope(type);

        chatInfoModelDao = new ChatInfoModelDao(chatInfoModelDaoConfig, this);
        contactModelDao = new ContactModelDao(contactModelDaoConfig, this);

        registerDao(ChatInfoModel.class, chatInfoModelDao);
        registerDao(ContactModel.class, contactModelDao);
    }
    
    public void clear() {
        chatInfoModelDaoConfig.clearIdentityScope();
        contactModelDaoConfig.clearIdentityScope();
    }

    public ChatInfoModelDao getChatInfoModelDao() {
        return chatInfoModelDao;
    }

    public ContactModelDao getContactModelDao() {
        return contactModelDao;
    }

}
